export const actions = {
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNED_UP: 'USER_SIGNED_UP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',

  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILED: 'USER_SIGN_IN_FAILED',

  GET_COLUMNS_SUCCESS: 'GET_COLUMNS_SUCCESS',
  GET_COLUMNS: 'GET_COLUMNS',
  GET_COLUMNS_FAILED: 'GET_COLUMNS_FAILED',
};
